#pragma once
// ============================================================================
// StudioFeel — Biquad Filter (Direct Form II Transposed)
// ============================================================================
// Single second-order IIR filter implementing the standard biquad transfer
// function: H(z) = (b0 + b1*z^-1 + b2*z^-2) / (1 + a1*z^-1 + a2*z^-2)
//
// Direct Form II Transposed is chosen for better numerical stability,
// especially at low frequencies and high sample rates.
//
// ALL methods on ProcessSample / Process are real-time safe:
// no allocation, no locking, no system calls.
// ============================================================================

#include <cstdint>
#include <cmath>
#include <cstring>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

namespace StudioFeel {

// ============================================================================
// Biquad Coefficients
// ============================================================================
// Stored in normalized form (a0 = 1.0 after normalization).
// Generated by Coefficients.h calculator from filter parameters.
// ============================================================================

struct BiquadCoefficients {
    float b0 = 1.0f;
    float b1 = 0.0f;
    float b2 = 0.0f;
    float a1 = 0.0f;   // Note: a0 is implicit (always 1.0 after normalization)
    float a2 = 0.0f;

    // Normalize all coefficients by a0, then discard a0
    void Normalize(float a0) {
        if (a0 != 0.0f && a0 != 1.0f) {
            const float inv = 1.0f / a0;
            b0 *= inv;
            b1 *= inv;
            b2 *= inv;
            a1 *= inv;
            a2 *= inv;
        }
    }

    // Identity (pass-through) coefficients
    static BiquadCoefficients Identity() {
        return { 1.0f, 0.0f, 0.0f, 0.0f, 0.0f };
    }

    bool IsIdentity() const {
        return b0 == 1.0f && b1 == 0.0f && b2 == 0.0f
            && a1 == 0.0f && a2 == 0.0f;
    }
};

// ============================================================================
// Biquad Filter
// ============================================================================

class BiquadFilter {
public:
    BiquadFilter() { Reset(); }
    ~BiquadFilter() = default;

    // Copy/move are fine — state is trivial
    BiquadFilter(const BiquadFilter&) = default;
    BiquadFilter& operator=(const BiquadFilter&) = default;

    // ========================================================================
    // Configuration (call from non-real-time thread, or at buffer boundaries)
    // ========================================================================

    void SetCoefficients(const BiquadCoefficients& coeff) {
        m_coeff = coeff;
    }

    const BiquadCoefficients& GetCoefficients() const {
        return m_coeff;
    }

    // Reset internal delay state (call when starting new stream or changing config)
    void Reset() {
        m_z1 = 0.0f;
        m_z2 = 0.0f;
    }

    // ========================================================================
    // Real-Time Processing (MUST be called from audio thread only)
    // ========================================================================

    // Process a single sample (Direct Form II Transposed)
    // This is the hot path — inlined for maximum performance.
    inline float ProcessSample(float input) {
        // Direct Form II Transposed:
        //   y[n] = b0 * x[n] + z1
        //   z1   = b1 * x[n] - a1 * y[n] + z2
        //   z2   = b2 * x[n] - a2 * y[n]
        const float output = m_coeff.b0 * input + m_z1;
        m_z1 = m_coeff.b1 * input - m_coeff.a1 * output + m_z2;
        m_z2 = m_coeff.b2 * input - m_coeff.a2 * output;
        return output;
    }

    // Process a block of interleaved samples for a single channel.
    // stride = number of channels (e.g., 2 for stereo).
    // pData points to this channel's first sample in the interleaved buffer.
    void Process(float* pData, uint32_t sampleCount, uint32_t stride = 1) {
        if (m_coeff.IsIdentity()) return;  // Skip pass-through

        for (uint32_t i = 0; i < sampleCount; ++i) {
            pData[i * stride] = ProcessSample(pData[i * stride]);
        }
    }

    // Process a contiguous (non-interleaved) block of samples
    void ProcessBlock(float* pData, uint32_t sampleCount) {
        if (m_coeff.IsIdentity()) return;

        for (uint32_t i = 0; i < sampleCount; ++i) {
            pData[i] = ProcessSample(pData[i]);
        }
    }

    // ========================================================================
    // Frequency Response Analysis (for UI visualization, NOT real-time)
    // ========================================================================

    // Compute magnitude response at a given frequency.
    // Returns magnitude in dB.
    float GetMagnitudeAt(float frequencyHz, float sampleRateHz) const {
        if (m_coeff.IsIdentity()) return 0.0f;

        // Evaluate H(z) at z = e^(j*omega) where omega = 2*pi*f/fs
        const double omega = 2.0 * M_PI * static_cast<double>(frequencyHz)
                           / static_cast<double>(sampleRateHz);
        const double cosW  = std::cos(omega);
        const double cos2W = std::cos(2.0 * omega);
        const double sinW  = std::sin(omega);
        const double sin2W = std::sin(2.0 * omega);

        // Numerator: b0 + b1*z^-1 + b2*z^-2
        const double numReal = m_coeff.b0 + m_coeff.b1 * cosW + m_coeff.b2 * cos2W;
        const double numImag = -(m_coeff.b1 * sinW + m_coeff.b2 * sin2W);

        // Denominator: 1 + a1*z^-1 + a2*z^-2
        const double denReal = 1.0 + m_coeff.a1 * cosW + m_coeff.a2 * cos2W;
        const double denImag = -(m_coeff.a1 * sinW + m_coeff.a2 * sin2W);

        const double numMagSq = numReal * numReal + numImag * numImag;
        const double denMagSq = denReal * denReal + denImag * denImag;

        if (denMagSq < 1e-20) return 0.0f;  // Avoid division by zero

        const double magnitudeDb = 10.0 * std::log10(numMagSq / denMagSq);
        return static_cast<float>(magnitudeDb);
    }

    // Compute phase response at a given frequency.
    // Returns phase in radians.
    float GetPhaseAt(float frequencyHz, float sampleRateHz) const {
        const double omega = 2.0 * M_PI * static_cast<double>(frequencyHz)
                           / static_cast<double>(sampleRateHz);
        const double cosW  = std::cos(omega);
        const double cos2W = std::cos(2.0 * omega);
        const double sinW  = std::sin(omega);
        const double sin2W = std::sin(2.0 * omega);

        const double numReal = m_coeff.b0 + m_coeff.b1 * cosW + m_coeff.b2 * cos2W;
        const double numImag = -(m_coeff.b1 * sinW + m_coeff.b2 * sin2W);
        const double denReal = 1.0 + m_coeff.a1 * cosW + m_coeff.a2 * cos2W;
        const double denImag = -(m_coeff.a1 * sinW + m_coeff.a2 * sin2W);

        const double numPhase = std::atan2(numImag, numReal);
        const double denPhase = std::atan2(denImag, denReal);

        return static_cast<float>(numPhase - denPhase);
    }

private:
    BiquadCoefficients m_coeff;

    // Delay state for Direct Form II Transposed
    float m_z1 = 0.0f;
    float m_z2 = 0.0f;
};

} // namespace StudioFeel
